name: Deploy Frontend to S3
on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Build React App
        working-directory: ./frontend
        run: npm run build
        env:
          VITE_API_BASE_URL: https://3.227.36.252.nip.io/api

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy to S3
        working-directory: ./frontend
        run: aws s3 sync dist/ s3://campushive-frontend-694069618970-us-east-1 --delete

      - name: Invalidate CloudFront Cache
        run: aws cloudfront create-invalidation --distribution-id E36CFE1XX3RT21 --paths "/*"
